Feature/uae 564 79 order comments
uae-rharrington/origin pull request #17
Opened 2018-07-20 13:28 UTC by ihor-ivchenko

2018-07-23 22:10 UTC, janepoltoratskaya requested changes

2018-07-23 22:10 UTC, janepoltoratskaya commented on app/code/ClassyLlama/OrderComments/Plugin/Model/ShippingInformationManagement.php
> +    public function aroundSaveAddressInformation(
What was the reason to use around? Can it be done with "after" plugin?

2018-07-23 22:10 UTC, janepoltoratskaya commented on app/code/ClassyLlama/OrderComments/Observer/QuoteManagement.php
> +        $quote = $observer->getEvent()->getQuote();
Please review Magento documentation and follow their approach if it's possible https://devdocs.magento.com/guides/v2.1/ext-best-practices/tutorials/copy-fieldsets.html

2018-07-23 22:10 UTC, janepoltoratskaya commented on app/code/ClassyLlama/OrderComments/etc/module.xml
> +			<sequence>
Please review tabs, it looks like there are more than 4 spaces for each.

2018-07-24 09:25 UTC, ihor-ivchenko commented on app/code/ClassyLlama/OrderComments/Observer/QuoteManagement.php
> +        $quote = $observer->getEvent()->getQuote();
@janepoltoratskaya I've tried, but this doesn't work for us

2018-07-31 08:22 UTC, merged